version: '3'

services:
  postgresql:
    restart: always
    image: library/postgres:10
    container_name: postgresql
    ports:
    - 5432:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
